### ISSUE TITLE
Document implemented backends 

### ISSUE THREAD

**Issue by francescalb** [EMMC-ASBL/tripper#157]
There is no intuitive place in the documentation where one can see which are the default backends available for Triplestore and how to defined them. This should be included somewhere.

eg.  backend = 'rdflib', 'collection' etc

**Comment by jesper-friis** [comment]
Is this addressed by the table added in PR #180, or do you want a API for listing available backends?

**Comment by francescalb** [comment]
> Is this addressed by the table added in PR #180, or do you want a API for listing available backends?

I think this is nice, but maybe even better if there is a comment in tripper.Triplestore to check the documentationf or available backends?

**Comment by jesper-friis** [comment]
> > Is this addressed by the table added in PR #180, or do you want a API for listing available backends?
> 
> I think this is nice, but maybe even better if there is a comment in tripper.Triplestore to check the documentationf or available backends?

Good point. Added it to PR #180.
