### ISSUE TITLE
Documentation CD (still) fails due to old python version

### ISSUE THREAD

**Issue by ajeklund** [EMMC-ASBL/tripper#193]
This is a follow-up issue on issue #191 with PR #192, which _should_ have solved the problem.

The problem is that the "External / Deploy 'latest' documentation" job fails because it tries to use 'mkdocs-material' version higher than 9.5.5 on python 3.7, which is incompatible.

Does this happen because the `publish-package-and-docs` job uses `SINTEF/ci-cd/.github/workflows/cd_release.yml@v1`? Seems like the latest version of that is v2.7.4.

**Comment by CasperWA** [comment]
This should have been updated in the `ci_cd_updated_main.yml` workflow.
