### ISSUE TITLE
Add the possibility to list all the databases inside a triplestore

### ISSUE THREAD

**Issue by xAlessandroC** [EMMC-ASBL/tripper#38]
It could be helpful, for the users, to list all the possible databases available for a specific triplestore.
However, since we want to introduce the concept of a database within the Triplestore interface (so that the user will refer to a specific database in a triplestore) should this feature be addressed by the tripper?
While all methods in the interface refer to a database, the list method should, somehow, refer only to the triplestore.

@jesper-friis How could we address this point?

**Comment by jesper-friis** [comment]
Make sense to me

**Comment by jesper-friis** [comment]
Added list_databases() together with create_database() and remove_database() in PR #34.
