### ISSUE TITLE
New Triplestore subclass

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/tripper#92]
Triplestore class starts to be large and has kind of two roles - both providing a common interface to different triplestore backends as well as providing functionality for working with data mapped to ontological concepts.

Would it make sense to create a new module that defines a Triplestore subclass to which we can move the data and mapping related methods, like:
  - map()
  - get_value()
  - add_data()
  - add_function()
  - add_interpolation_source()

What would be good names for the new Triplestore subclass? Datastore?

**Comment by alfredoisg** [comment]
In `tripper/` create new `name.py` containing a class `name`. `name` has the methods:
- get_value()
- add_data()

which should be moved from `tripper/triplestore.py`.

Suggestions for `name` from ChatGPT: 
- `OntologyDataHandler`
- `TriplestoreDataHandler`
- `SemanticDataHandler`

**Comment by alfredoisg** [comment]
Hei @jesper-friis
The methods you listed are not in #main yet but in #91 (not merged yet)
